SCREEN_SIZE = (700, 400)
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 1200

TOTAL_ROAD_WIDTH = SCREEN_WIDTH * 0.70
TOTAL_LAWN_WIDTH = SCREEN_WIDTH - TOTAL_ROAD_WIDTH
LAWN_MARGIN_WIDTH = TOTAL_LAWN_WIDTH // 2
LANE_WIDTH = 50